use `google-github-actions/setup-gcloud` to upload

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,6 +5,10 @@ on:
     branches:
       - releases/main
 
+env:
+  SITE_DIST_FOLDER: "./apps/portfolio/dist"
+  SITE_BUCKET_NAME: "www.nurliman.dev"
+
 jobs:
   deploy:
     permissions:
@@ -35,6 +39,9 @@ jobs:
       - name: Build
         run: pnpm build
 
+      - name: "Validate directory not empty"
+        run: '[ "$(ls -A ${{ env.SITE_DIST_FOLDER }})" ] && echo "Files exist - all good." || (echo "Directory is empty - aborting." && exit 1)'
+
       - id: "auth"
         name: "Authenticate to Google Cloud"
         uses: "google-github-actions/auth@v0"
@@ -42,9 +49,8 @@ jobs:
           workload_identity_provider: "${{ secrets.GCP_WIF_PROVIDER }}"
           service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
 
-      - id: "upload-website"
-        uses: "google-github-actions/upload-cloud-storage@v0"
-        with:
-          path: "./apps/portfolio/dist"
-          destination: "www.nurliman.dev"
-          parent: false
+      - name: "Set up Cloud SDK"
+        uses: "google-github-actions/setup-gcloud@v0"
+
+      - name: "Upload Site"
+        run: "gsutil rsync -d -r ${{ env.SITE_DIST_FOLDER }} gs://${{ env.SITE_BUCKET_NAME }}"
